### ISSUE TITLE
RuntimeError: affine matrix has wrong number of rows`

### ISSUE THREAD

**Issue by yunhaizhu** [jacobkie/2018DSB#1]
when run 'python3 train_ext.py', meet some issues, is my environment not correct?
can you help to provide your running environment? by running the 'pip3 list'. 

`
Epoch 1/100
Traceback (most recent call last):
  File "train_ext.py", line 62, in <module>
    train_1s()
  File "train_ext.py", line 59, in train_1s
    model.train_generator(tr_ms1, val_ms1, 1e-3, 100, 'all')
  File "/2th-DSB2018/script_final/model_rcnn_weight.py", line 495, in train_generator
    use_multiprocessing=False,
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2145, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 770, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 635, in _data_generator_task
    generator_output = next(self._generator)
  File "/medical_data/yunhai/2th-DSB2018/script_final/model_ms1.py", line 42, in generator_1s_v11
    image, mask = next(gen)
  File "train_ext.py", line 34, in train_generator
    image, mask = next(gen)
  File "/2th-DSB2018/script_final/generator.py", line 64, in data_generator_multi
    zoom_range = config.ZOOM_RANGE)
  File "/2th-DSB2018/script_final/preprocess.py", line 198, in affine_transform_batch
    xt = scipy.ndimage.affine_transform(x, matrix, order=1, cval=-512)
  File "/usr/local/lib/python3.5/dist-packages/scipy/ndimage/interpolation.py", line 449, in affine_transform
    raise RuntimeError('affine matrix has wrong number of rows')
RuntimeError: affine matrix has wrong number of rows

`

**Comment by lc12315** [comment]
你是中国人吧，我也是和你遇到一样的问题，你解决了吗？请回复我，我的邮箱是1061428541@qq.com，
希望大家共同进步
